### ISSUE TITLE
Increase splash screen duration

### ISSUE THREAD

**Issue by ferdicus** [spencercarli/react-native-splash-screen-demo#1]
Hey @spencercarli, thanks for  this repo and the accompanying medium post.
I managed to get it working and it looks pretty nice.

Do you know of a way to increase the duration the splashscreen is display?

Right now it disappears rather quickly and I'm planing on doing some checking in the background when the app is being opened.

Thanks again!

**Comment by spencercarli** [comment]
I wouldn't really suggest doing that, your app should handle loading rather than the splash screen, but if you really want to check out [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen).
