### ISSUE TITLE
How to Remove White Screen after Splash Screen in React Native For Android?

### ISSUE THREAD

**Issue by saeedhei** [spencercarli/react-native-splash-screen-demo#2]
Link of My Question in [Stackoverflow](https://stackoverflow.com/questions/44384491/how-to-remove-white-screen-after-splash-screen-in-react-native-for-android)

I have a Default react native project and I installed From This Turorial and I just added Splash Screen to my Project with This Tutorial, But I Got First:

- 0.5 secend splash screen photo
- Then 1.5 secend white screen
- And after that my app started,

**What is the best and standart way to fix This problem?** I need Just 1 secend Standard preload for Splash Screen and after That app Start, I read more article but i coudn't fix by react native.

**Comment by saeedhei** [comment]
[Solved](https://github.com/crazycodeboy/react-native-splash-screen)

**Comment by rochapablo** [comment]
@saeedhei what did you do? Have you just installed the plugin?

**Comment by saeedhei** [comment]
Yes
