### ISSUE TITLE
getting splash screen issue when i was release apk

### ISSUE THREAD

**Issue by lavarajallu** [spencercarli/react-native-splash-screen-demo#7]
`Execution failed for task ':react-native-splash-screen:verifyReleaseResources'`

  Copying resources from program jar [/Users/stellent/Documents/Iyantra/android/app/build/intermediates/transforms/mergeJavaRes/release/0.jar] (filtered)
Printing classes to [/Users/stellent/Documents/Iyantra/android/app/build/outputs/mapping/release/dump.txt]...
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.
    
error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-splash-screen:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
57 actionable tasks: 9 executed, 48 up-to-date
STELLENTsMini10:android stellent$

**Comment by lavarajallu** [comment]
Copying resources from program jar [/Users/stellent/Documents/Iyantra/android/app/build/intermediates/transforms/mergeJavaRes/release/0.jar] (filtered)
Printing classes to [/Users/stellent/Documents/Iyantra/android/app/build/outputs/mapping/release/dump.txt]...
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.
    
/Users/stellent/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/3493cf617c27249e283d26a08e2be510/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.
    
error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-splash-screen:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
57 actionable tasks: 9 executed, 48 up-to-date
STELLENTsMini10:android stellent$

**Comment by spencercarli** [comment]
I think you meant to open this on the package repo for `react-native-splash-screen`?
