### ISSUE TITLE
symbol erro

### ISSUE THREAD

**Issue by lakshman2017** [spencercarli/react-native-splash-screen-demo#9]
/SplashActivity.java:12: error: cannot find symbol
        Intent intent = new Intent(this, MainActivity.class);
                                         ^
  symbol:   class MainActivity
  location: class SplashActivity
1 error

**Comment by spencercarli** [comment]
You need to [import Intent](https://github.com/spencercarli/react-native-splash-screen-demo/blob/master/android/app/src/main/java/com/splashscreendemo/SplashActivity.java#L3)
